# Generated by Django 4.2.29 on 2026-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Admin (Group Level)'), ('BRANCH_ADMIN', 'Branch Admin (School Level)'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=20),
        ),
    ]
