# Generated by Django 4.2.29 on 2026-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bulkactionlog_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces the user to change their password on next login.'),
        ),
    ]
