# Generated by Django 4.2.29 on 2026-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='admission_no_format',
            field=models.CharField(choices=[('YEAR_BRANCH_SEQ', 'YEAR/BRANCH/001'), ('BRANCH_YEAR_SEQ', 'BRANCH/YEAR/001'), ('YEAR_SEQ', 'YEAR/001'), ('PREFIX_SEQ', 'PREFIX-001')], default='YEAR_BRANCH_SEQ', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='admission_no_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
