# Generated by Django 4.2.29 on 2026-04-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_branch_admission_no_format_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('tenant', 'name')},
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='branch',
        ),
    ]
