# Generated by Django 4.2.29 on 2026-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_globalsetting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_academic_year_per_tenant'),
        ),
    ]
