# Generated by Django 4.2.29 on 2026-04-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0006_academicyear_unique_active_academic_year_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_academic_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], default='PLANNING', max_length=20),
        ),
    ]
