# Generated by Django 4.2.29 on 2026-05-05 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_zone_branch_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAdmissionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount collected as admission fee at enrollment (separate from class fee structure).', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_admission_fees', to='tenants.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fees', to='tenants.branch')),
            ],
            options={
                'unique_together': {('branch', 'academic_year')},
            },
        ),
    ]
