# Generated by Django 4.2.29 on 2026-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_APPROVAL', 'Pending Approval'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('DETAINED', 'Detained')], default='ACTIVE', max_length=20),
        ),
    ]
