# Generated by Django 4.2.29 on 2026-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc_aadhaar_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_birth_cert_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_bonafide_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_caste_cert_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_tc_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_ay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'branch', 'academic_year', 'status'], name='students_st_tenant__9ab29b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'class_section', 'status'], name='students_st_branch__72ae7c_idx'),
        ),
    ]
