# Generated by Django 4.2.29 on 2026-04-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_academicyear_closed_at_academicyear_closed_by_and_more'),
        ('students', '0009_student_parent_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_APPROVAL', 'Pending Approval'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('DETAINED', 'Detained'), ('DROPOUT', 'Dropout')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('DETAINED', 'Detained'), ('DROPOUT', 'Dropout'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='tenants.academicyear')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='students.classsection')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='students.studentacademicrecord')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year__start_date'],
                'indexes': [models.Index(fields=['academic_year', 'status'], name='students_st_academi_adfd4d_idx'), models.Index(fields=['class_section', 'status'], name='students_st_class_s_48819a_idx'), models.Index(fields=['student', 'academic_year'], name='students_st_student_a49ac5_idx')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassPromotionMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_grade', models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11_SCIENCE', 'Grade 11 Science'), ('11_COMMERCE', 'Grade 11 Commerce'), ('11_ARTS', 'Grade 11 Arts'), ('12_SCIENCE', 'Grade 12 Science'), ('12_COMMERCE', 'Grade 12 Commerce'), ('12_ARTS', 'Grade 12 Arts')], max_length=20)),
                ('to_grade', models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11_SCIENCE', 'Grade 11 Science'), ('11_COMMERCE', 'Grade 11 Commerce'), ('11_ARTS', 'Grade 11 Arts'), ('12_SCIENCE', 'Grade 12 Science'), ('12_COMMERCE', 'Grade 12 Commerce'), ('12_ARTS', 'Grade 12 Arts')], max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_maps', to='tenants.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_maps', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_maps', to='tenants.tenant')),
            ],
            options={
                'ordering': ['from_grade'],
                'unique_together': {('branch', 'academic_year', 'from_grade')},
            },
        ),
    ]
