# Generated by Django 4.2.29 on 2026-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_admissionapplication_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
