# Generated by Django 4.2.29 on 2026-04-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ABSENCE_ALERT', 'Absence Alert'), ('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('HOMEWORK_POSTED', 'Homework Posted'), ('PASSWORD_RESET', 'Password Reset'), ('WELCOME_ENROLLMENT', 'Welcome Enrollment'), ('FEE_REMINDER_3DAYS', 'Fee Reminder 3 Days')], max_length=30)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.branch')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ABSENCE_ALERT', 'Absence Alert'), ('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('HOMEWORK_POSTED', 'Homework Posted'), ('PASSWORD_RESET', 'Password Reset'), ('WELCOME_ENROLLMENT', 'Welcome Enrollment'), ('FEE_REMINDER_3DAYS', 'Fee Reminder 3 Days')], max_length=30)),
                ('whatsapp_template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_vars', models.JSONField(blank=True, null=True)),
                ('sms_template', models.TextField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('email_body_html', models.TextField(blank=True, null=True)),
                ('push_title', models.CharField(blank=True, max_length=100, null=True)),
                ('push_body', models.CharField(blank=True, max_length=200, null=True)),
                ('is_sms_enabled', models.BooleanField(default=False)),
                ('is_email_enabled', models.BooleanField(default=True)),
                ('is_push_enabled', models.BooleanField(default=True)),
                ('is_whatsapp_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants.branch')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'event_type')},
            },
        ),
    ]
