# Generated by Django 4.2.29 on 2026-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ABSENCE_ALERT', 'Absence Alert'), ('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('HOMEWORK_POSTED', 'Homework Posted'), ('PASSWORD_RESET', 'Password Reset'), ('WELCOME_ENROLLMENT', 'Welcome Enrollment'), ('FEE_REMINDER_3DAYS', 'Fee Reminder 3 Days'), ('CUSTOM_ANNOUNCEMENT', 'Custom Announcement')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ABSENCE_ALERT', 'Absence Alert'), ('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('HOMEWORK_POSTED', 'Homework Posted'), ('PASSWORD_RESET', 'Password Reset'), ('WELCOME_ENROLLMENT', 'Welcome Enrollment'), ('FEE_REMINDER_3DAYS', 'Fee Reminder 3 Days'), ('CUSTOM_ANNOUNCEMENT', 'Custom Announcement')], max_length=30),
        ),
    ]
