# Generated by Django 4.2.29 on 2026-04-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('CLASSWORK', 'Classwork'), ('PROJECT', 'Project'), ('REVISION', 'Revision'), ('READING', 'Reading')], default='HOMEWORK', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.classsection')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_posted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='timetable.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file_size_kb', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homework')),
            ],
        ),
    ]
