# Generated by Django 4.2.29 on 2026-04-21 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAcknowledgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='homework.homework')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('homework', 'parent')},
            },
        ),
    ]
