# Generated by Django 4.2.29 on 2026-04-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_parent_address_fields'),
        ('tenants', '0006_academicyear_unique_active_academic_year_per_tenant'),
        ('timetable', '0002_classsubjectdemand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubjectdemand',
            unique_together={('class_section', 'subject', 'academic_year')},
        ),
    ]
