# Generated by Django 4.2.29 on 2026-04-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_globalsetting'),
        ('students', '0009_student_parent_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_point', models.CharField(default='School', max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Total route distance in km', max_digits=6)),
                ('stops', models.JSONField(blank=True, default=list, help_text='Ordered list of stop names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransportRateSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Monthly fee in ₹ for this distance slab', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_rate_slabs', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_rate_slabs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['min_km'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text="Student's specific distance from school", max_digits=6)),
                ('pickup_point', models.CharField(blank=True, max_length=200)),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Resolved monthly fee from rate slab', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('opted_at', models.DateTimeField(auto_now_add=True)),
                ('opted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_optins', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='transport.transportroute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student')),
            ],
            options={
                'ordering': ['-opted_at'],
            },
        ),
    ]
