# Generated by Django 4.2.29 on 2026-04-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttransport',
            name='route',
        ),
        migrations.DeleteModel(
            name='TransportRoute',
        ),
    ]
