# Generated by Django 4.2.29 on 2026-04-01 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
            },
        ),
    ]
