# Generated by Django 4.2.29 on 2026-04-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_academicyear_unique_active_academic_year_per_tenant'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='voucher_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('branch', 'voucher_number')},
        ),
    ]
