# Generated by Django 4.2.29 on 2026-04-01 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('students', '0001_initial'),
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentconcession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentconcession',
            name='concession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_concessions', to='fees.feeconcession'),
        ),
        migrations.AddField(
            model_name='studentconcession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_items', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructureitem',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='applies_to_categories',
            field=models.ManyToManyField(blank=True, related_name='concessions', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructureitem',
            unique_together={('structure', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('branch', 'academic_year', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='feeinvoice',
            unique_together={('branch', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('branch', 'code')},
        ),
    ]
