# Generated by Django 4.2.29 on 2026-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feeapprovalrequest_studentfeeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinvoice',
            name='month',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='grade',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
