# Generated by Django 4.2.29 on 2026-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feeinvoice_month_alter_feeinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'month'], name='fees_feeinv_student_5e2512_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['branch', 'status', 'due_date'], name='fees_feeinv_branch__e5d3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['tenant', 'status', 'outstanding_amount'], name='fees_feeinv_tenant__b45d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='fees_paymen_invoice_438878_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'payment_date'], name='fees_paymen_branch__da2a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id__isnull', False)), fields=('razorpay_payment_id',), name='unique_razorpay_payment_id'),
        ),
    ]
