# Generated by Django 4.2.29 on 2026-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_academicyear_unique_together_and_more'),
        ('fees', '0006_documentsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Ensures exactly-once payment processing.', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='fees_paymen_idempot_604514_idx'),
        ),
    ]
