# Generated by Django 4.2.29 on 2026-04-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_status_studentacademicrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_academicyear_closed_at_academicyear_closed_by_and_more'),
        ('fees', '0007_payment_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCarryForward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carry_forward_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('WRITTEN_OFF', 'Written Off')], default='PENDING', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('written_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_carry_forwards', to='tenants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_carry_forwards', to=settings.AUTH_USER_MODEL)),
                ('source_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_carry_forwards', to='tenants.academicyear')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carry_forwards', to='students.studentacademicrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards', to='students.student')),
                ('target_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_carry_forwards', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_carry_forwards', to='tenants.tenant')),
            ],
            options={
                'ordering': ['source_academic_year__start_date'],
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeeWriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_write_offs', to='tenants.branch')),
                ('carry_forward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='fees.feecarryforward')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='fees.feeinvoice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_write_offs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYearClosingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='IN_PROGRESS', max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('promoted_count', models.IntegerField(default=0)),
                ('detained_count', models.IntegerField(default=0)),
                ('dropout_count', models.IntegerField(default=0)),
                ('graduated_count', models.IntegerField(default=0)),
                ('carry_forwards_created', models.IntegerField(default=0)),
                ('total_carry_forward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_details', models.JSONField(default=dict)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_logs', to='tenants.academicyear')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_closings', to=settings.AUTH_USER_MODEL)),
                ('target_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_closing_logs', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_type', models.CharField(choices=[('CURRENT_YEAR', 'Current Year Fee'), ('PREVIOUS_YEAR_DUES', 'Previous Year Dues')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carry_forward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='fees.feecarryforward')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='fees.feeinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['payment'], name='fees_paymen_payment_245db4_idx'), models.Index(fields=['invoice'], name='fees_paymen_invoice_94095a_idx'), models.Index(fields=['carry_forward'], name='fees_paymen_carry_f_96054f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='feecarryforward',
            index=models.Index(fields=['student', 'status'], name='fees_feecar_student_2bb31a_idx'),
        ),
        migrations.AddIndex(
            model_name='feecarryforward',
            index=models.Index(fields=['target_academic_year', 'status'], name='fees_feecar_target__013dca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feecarryforward',
            unique_together={('student', 'source_academic_year', 'target_academic_year')},
        ),
    ]
