# Generated by Django 4.2.29 on 2026-04-27 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_academicyear_closed_at_academicyear_closed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('FEE_RECEIPT', 'Fee Receipt'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate')], max_length=50)),
                ('mode', models.CharField(choices=[('CONFIG', 'Standard Configuration (Safe)'), ('HTML', 'Raw HTML (Advanced)')], default='CONFIG', max_length=20)),
                ('config_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='tenants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('tenant', 'branch', 'type', 'is_default')},
            },
        ),
    ]
