# Generated by Django 4.2.29 on 2026-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'branch', 'type'), name='unique_default_template_per_type'),
        ),
    ]
